filebeat.prospectors:

- input_type: log
  #document_type: eslog
  paths:
    # - /var/log/eslog/*.log
    - /var/log/app/*.log

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

#================================ Outputs =====================================
# output.elasticsearch:
#   hosts: ["http://es:9200"]
#   template.overwrite: false
  #pipeline: ""
  #protocol: "http"
  #username: "elastic"
  #password: "changeme"

output.logstash:
  hosts: ["logstash:5043"]
  template.overwrite: false
